# Generated by Django 5.0.4 on 2024-05-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_id',
            new_name='commenter',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.comment'),
        ),
    ]
