# Generated by Django 5.0.4 on 2024-05-30 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_seat_theater_remove_comment_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.seat'),
        ),
    ]
