# Generated by Django 5.0.4 on 2024-05-30 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='parent_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='articles.review'),
        ),
    ]
