# Generated by Django 5.0.6 on 2024-05-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('width', models.FloatField(default=20)),
                ('height', models.FloatField(default=20)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='articles.theater')),
            ],
        ),
    ]
