# Generated by Django 5.0.6 on 2024-05-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birthday_user_gender_user_name_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('남성', 'male'), ('여성', 'female'), ('또 다른 성', 'other')], max_length=10, null=True),
        ),
    ]
